### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Ibooted** [Lawxsz/prysmax#2]
whenever I compile, it throws this error:
Compiling...
Pyarmor 8.0+ has only 3 commands: gen, reg, cfg
Please replace `pyarmor` with `pyarmor-7` to run old commands
File successfully compiled!

**Comment by Lawxsz** [comment]
hello that happens because of your pyarmor version, your file has already been compiled because if you don't have version 6.x the other command is used automatically, so it is already compiled.
